### ISSUE TITLE
action requires a webhook token, but none is available

### ISSUE THREAD

**Issue by Srivathsav-max** [Sayrix/Ticket-Bot#101]
qRdotcomError [WebhookTokenUnavailable]: This action requires a webhook token, but none is available.
    at Webhook.send (C:\ticket-bot\node_modules\discord.js\src\structures\Webhook.js:206:28)
    at Client.log (C:\ticket-bot\utils\logs.js:47:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'WebhookTokenUnavailable'
}
Error [WebhookTokenUnavailable]: This action requires a webhook token, but none is available.
    at Webhook.send (C:\ticket-bot\node_modules\discord.js\src\structures\Webhook.js:206:28)
    at Client.log (C:\ticket-bot\utils\logs.js:60:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'WebhookTokenUnavailable'
}

**Comment by Sayrix** [comment]
try to restart your bot

**Comment by Srivathsav-max** [comment]
I restarted bot several times but getting same issue



________________________________

**Comment by Sayrix** [comment]
Check your config you probably did something wrong
