### ISSUE TITLE
Ticket cant be made. (Says the bot is thinking when you click on it)

### ISSUE THREAD

**Issue by Tireddylann** [Sayrix/Ticket-Bot#127]
This is my error code:
```
      throw er; // Unhandled 'error' event
      ^

CombinedPropertyError: Received one or more errors
    at ObjectValidator.handleIgnoreStrategy (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1252:70)
    at ObjectValidator.handleStrategy (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1105:47)
    at ObjectValidator.handle (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1205:17)
    at ObjectValidator.parse (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:201:88)
    at /root/Ticket-Bot/node_modules/@discordjs/builders/dist/index.js:918:163
    at Array.map (<anonymous>)
    at StringSelectMenuBuilder.addOptions (/root/Ticket-Bot/node_modules/@discordjs/builders/dist/index.js:918:34)
    at StringSelectMenuBuilder.addOptions (/root/Ticket-Bot/node_modules/discord.js/src/structures/StringSelectMenuBuilder.js:48:18)
    at Object.execute (/root/Ticket-Bot/events/interactionCreate.js:321:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errors: [
    [
      'label',
      ValidationError: Expected a string primitive
          at StringValidator.handle (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1705:70)
          at StringValidator.run (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:187:23)
          at runPredicate (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1215:32)
          at ObjectValidator.handleIgnoreStrategy (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1225:9)
          at ObjectValidator.handleStrategy (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1105:47)
          at ObjectValidator.handle (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1205:17)
          at ObjectValidator.parse (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:201:88)
          at /root/Ticket-Bot/node_modules/@discordjs/builders/dist/index.js:918:163
          at Array.map (<anonymous>)
          at StringSelectMenuBuilder.addOptions (/root/Ticket-Bot/node_modules/@discordjs/builders/dist/index.js:918:34) {
        validator: 's.string',
        given: undefined
      }
    ],
    [
      'value',
      ValidationError: Expected a string primitive
          at StringValidator.handle (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1705:70)
          at StringValidator.run (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:187:23)
          at runPredicate (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1215:32)
          at ObjectValidator.handleIgnoreStrategy (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1225:9)
          at ObjectValidator.handleStrategy (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1105:47)
          at ObjectValidator.handle (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:1205:17)
          at ObjectValidator.parse (/root/Ticket-Bot/node_modules/@sapphire/shapeshift/dist/index.js:201:88)
          at /root/Ticket-Bot/node_modules/@discordjs/builders/dist/index.js:918:163
          at Array.map (<anonymous>)
          at StringSelectMenuBuilder.addOptions (/root/Ticket-Bot/node_modules/@discordjs/builders/dist/index.js:918:34) {
        validator: 's.string',
        given: undefined
      }
    ]
  ]
}

Node.js v18.15.0
```
Please help

**Comment by Sayrix** [comment]
Check your config you did something wrong
