### ISSUE TITLE
Bot crashes if webhook already exist for log channel that isn't accessible by the bot

### ISSUE THREAD

**Issue by zhiyan114** [Sayrix/Ticket-Bot#156]
In certain condition, a webhook that is created under the log channel may be inaccessible by the ticket bot; thus, throwing the error. Since the algorithm detects that the channel already has a webhook, it will not create one that is usable.

I can push out a fix to my current PR (#155)

Context:
musiker15 - 

```
node index.js

████████╗██╗ ██████╗██╗  ██╗███████╗████████╗    ██████╗  ██████╗ ████████╗
╚══██╔══╝██║██╔════╝██║ ██╔╝██╔════╝╚══██╔══╝    ██╔══██╗██╔═══██╗╚══██╔══╝
   ██║   ██║██║     █████╔╝ █████╗     ██║       ██████╔╝██║   ██║   ██║   
   ██║   ██║██║     ██╔═██╗ ██╔══╝     ██║       ██╔══██╗██║   ██║   ██║   
   ██║   ██║╚██████╗██║  ██╗███████╗   ██║       ██████╔╝╚██████╔╝   ██║   
   ╚═╝   ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝   ╚═╝       ╚═════╝  ╚═════╝    ╚═╝
                 https://github.com/Sayrix/ticket-bot

Connecting to Discord...
🚀  The bot is ready! Logged in as MSK Support#6882 (456456456456)
🌟  You can leave a star on GitHub: https://github.com/Sayrix/ticket-bot 
📖  Documentation: https://doc.ticket.pm 
⛅  Host your ticket-bot by being a sponsor from 1$/month: https://github.com/sponsors/Sayrix 
💖  Thanks to our sponsors: VespidEmperor, BlutwurstPro, Musiker15, LostServices, MCZ-Le-J, nunofaria13, ZeaDRGOD, BgMonsterXx, GapsaW, Lucas6635, nicolasbaud
✅  Connected to WebSocket server.
✅  Successfully registered application commands.
TypeError: Cannot read properties of undefined (reading 'send')
    at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:42:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'send')
      at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:42:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} undefined
TypeError: Cannot read properties of undefined (reading 'send')
    at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:80:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'send')
      at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:80:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} undefined
TypeError: Cannot read properties of undefined (reading 'send')
    at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:99:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'send')
      at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:99:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} undefined
```

**Comment by zhiyan114** [comment]
Avoid opening another issues, there also seems to be a bug where empty `url` config prevents the status from updating.
