### ISSUE TITLE
Bot throws error after running it for a period of time

### ISSUE THREAD

**Issue by zhiyan114** [Sayrix/Ticket-Bot#180]
Problem
-------------------------
After running a bot for a period of time, the bot throws the following errors:
```sh
TypeError: Cannot read properties of undefined (reading 'config')
    at Timeout.setStatus [as _onTimeout] (F:\Ticket-Bot\dist\events\ready.js:163:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```
```sh
❌  WebSocket Error: Error: read ECONNRESET
❌  WebSocket Error: 1006
✅  Connected to WebSocket server.
TypeError: this.telemetry is not a function
    at WebSocketClient.<anonymous> (F:\Ticket-Bot\dist\events\ready.js:217:18)
    at WebSocketClient.emit (node:events:513:28)
    at WebSocketClient.succeedHandshake (F:\Ticket-Bot\node_modules\websocket\lib\WebSocketClient.js:348:10)
    at WebSocketClient.validateHandshake (F:\Ticket-Bot\node_modules\websocket\lib\WebSocketClient.js:332:10)
    at ClientRequest.handleRequestUpgrade (F:\Ticket-Bot\node_modules\websocket\lib\WebSocketClient.js:261:14)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketOnData (node:_http_client:582:11)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
```

It seems like the telemetry issue happens after the websocket errors.

Solution
-------------------------
[Unknown] - In Progress

**Comment by Sayrix** [comment]
You should try catch the websocket function

**Comment by zhiyan114** [comment]
I feel like there's something to do with how `setInterval` and `setTimeout` are handled in NodeJS since both issue happens when the code is being call by either one of it.
I'll go head and play around with it to confirm that statement, and if it's true then it's NodeJS engine bug.

**Comment by Sayrix** [comment]
Yean but that's strange because in JS when the websocket have an error he just try to reconnect to it not throwing error

**Comment by zhiyan114** [comment]
This is def a a strange bug. We can confirm two things here:
1. `config` is not undefined because it's being read when the bot is first turned on
2. `this.telemetry` is always a function because nowhere in any of the codes changed that (and it's a horrible practice anyway)
3. Error seems to only happen if the method is called inside the two time-based callback functions.

**Comment by zhiyan114** [comment]
Yup confirmed it. I'll push out a fix.
