### ISSUE TITLE
Bot Not Starting

### ISSUE THREAD

**Issue by Zaiot** [Sayrix/ticket-bot#2]
i wil start the bot and the bot wil not stating...
![image](https://user-images.githubusercontent.com/92209198/141159162-20df8b47-650d-4837-ae74-9d0f8ffc83fc.png)

**Comment by Sayrix** [comment]
Did you have discord.js v13 and node.js 16+ ?

**Comment by Zaiot** [comment]
> Did you have discord.js v13 and node.js 16+ ?

I Have now node.js 16+ how i can get the discord.js v13?

**Comment by Sayrix** [comment]
`npm i discord.js@13.3.1`

**Comment by Zaiot** [comment]
> `![image](https://user-images.githubusercontent.com/92209198/141368804-bd130f60-d59c-4a50-9438-960c98b476d7.png)`

Not working...

**Comment by Zaiot** [comment]
> `npm i discord.js@13.3.1`

node_modules\discord.js\src\client\websocket\WebSocketManager.js:249
        throw new Error(WSCodes[error.code]);
              ^

Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\Kristof\Desktop\DISCORD BOTS\Team Release NL Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:249:15)
    at async Client.login (C:\Users\Kristof\Desktop\DISCORD BOTS\Team Release NL Bot\node_modules\discord.js\src\client\Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}

Node.js v17.1.0

this is the error

**Comment by Sayrix** [comment]
You need to have this box checked
![image](https://user-images.githubusercontent.com/43046854/141369087-44aa428e-47b9-4750-8b38-342762e50cde.png)

**Comment by Zaiot** [comment]
> You need to have this box checked ![image](https://user-images.githubusercontent.com/43046854/141369087-44aa428e-47b9-4750-8b38-342762e50cde.png)

error..

events\ready.js:31
    oniChan.bulkDelete(100).then(() => {
            ^

TypeError: Cannot read properties of undefined (reading 'bulkDelete')
    at Object.execute (C:\Users\Kristof\Desktop\DISCORD BOTS\Team Release NL Bot\events\ready.js:31:13)
    at Client.<anonymous> (C:\Users\Kristof\Desktop\DISCORD BOTS\Team Release NL Bot\index.js:29:46)
    at Client.emit (node:events:390:28)
    at WebSocketManager.triggerClientReady (C:\Users\Kristof\Desktop\DISCORD BOTS\Team Release NL Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:383:17)
    at WebSocketManager.checkShardsReady (C:\Users\Kristof\Desktop\DISCORD BOTS\Team Release NL Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:366:10)
    at WebSocketShard.<anonymous> (C:\Users\Kristof\Desktop\DISCORD BOTS\Team Release NL Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:188:14)
    at WebSocketShard.emit (node:events:390:28)
    at WebSocketShard.checkReady (C:\Users\Kristof\Desktop\DISCORD BOTS\Team Release NL Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:474:12)
    at WebSocketShard.onPacket (C:\Users\Kristof\Desktop\DISCORD BOTS\Team Release NL Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:446:16)
    at WebSocketShard.onMessage (C:\Users\Kristof\Desktop\DISCORD BOTS\Team Release NL Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10)

Node.js v17.1.0

**Comment by Sayrix** [comment]
That's a configuration problem on your part

**Comment by Zaiot** [comment]
> That's a configuration problem on your part

how to do i can fixed?

**Comment by Sayrix** [comment]
By configuring well the config.json

**Comment by Zaiot** [comment]
> By configuring well the config.json

what should i check?

**Comment by Sayrix** [comment]
All the config

**Comment by Zaiot** [comment]
> All the config

hij toont de error bij dit:

    oniChan.bulkDelete(100).then(() => {
      sendTicketMSG()
    })
  },
};

**Comment by Zaiot** [comment]
> All the config

it shows the error with this

    oniChan.bulkDelete(100).then(() => {
      sendTicketMSG()
    })
  },
};

**Comment by kuriakoschai** [comment]
C:\Users\user\Desktop\ticket-bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:256
        throw new Error(WSCodes[error.code]);
              ^

Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\user\Desktop\ticket-bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:256:15)
    at async Client.login (C:\Users\user\Desktop\ticket-bot-main\node_modules\discord.js\src\client\Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}

Any idea why ?

**Comment by KOVO-TECH** [comment]
Did you join bot on server?
