### ISSUE TITLE
Hello guys, i have this error

### ISSUE THREAD

**Issue by Pifftane** [Sayrix/Ticket-Bot#346]
**Describe the bug**

**To Reproduce**

**My config**
Your config but without your bot token!

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Pifftane** [comment]
DiscordAPIError[50035]: Invalid Form Body
components[0].components[0].options[2][SELECT_COMPONENT_OPTION_VALUE_DUPLICATED]: The specified option value is already used
    at handleErrors (C:\Users\Administrator\Desktop\Ticket-Bot-main\node_modules\@discordjs\rest\dist\index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (C:\Users\Administrator\Desktop\Ticket-Bot-main\node_modules\@discordjs\rest\dist\index.js:1120:23)
    at async SequentialHandler.queueRequest (C:\Users\Administrator\Desktop\Ticket-Bot-main\node_modules\@discordjs\rest\dist\index.js:953:14)
    at async _REST.request (C:\Users\Administrator\Desktop\Ticket-Bot-main\node_modules\@discordjs\rest\dist\index.js:1266:22)
    at async InteractionWebhook.editMessage (C:\Users\Administrator\Desktop\Ticket-Bot-main\node_modules\discord.js\src\structures\Webhook.js:339:15)
    at async ButtonInteraction.editReply (C:\Users\Administrator\Desktop\Ticket-Bot-main\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:158:17) {
  requestBody: {
    files: [],
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: [Array],
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { components: [Object] }
  },
  code: 50035,
  status: 400,
  method: 'PATCH',
  url: 'https://discord.com/api/v10/webhooks/1224500904686915584/aW50ZXJhY3Rpb246MTIyNDUxMzEyNjc3NTM5MDI3MTpuZXVBZlRBSHMzaDQ3U3EybFhpZUtJYVlJRE1sbkVBT0NKaDBPYlFRbWVGaG42WnM1N0hkcFRRdVNRNUVGVVhHRHRMbHZFaVBtQWZnTWhmNUY2RWhXY1cxR2J6MnhxVGNaVG5EUzJlY0Y2blJKMHZnVG1YenFsSU1WOHRJR0pGTw/messages/@original'
}

**Comment by zhiyan114** [comment]
This bug report is very unhelpful!
The report already has a template that you can fill up, which will help us identify the issue. So when you submit another report, please complete that next time. The title should also describe the issue in very few words.

For your issue, this is not a bug. If you take a closer look, you'll see `components[0].components[0].options[2][SELECT_COMPONENT_OPTION_VALUE_DUPLICATED]: The specified option value is already used`, which means one of ur config field is duplicated. But again, you did not complete anything from the template so this answer may not be accurate.

For further assistant, use the discord #community-support channel instead.
