### ISSUE TITLE
Error starting the bot

### ISSUE THREAD

**Issue by ImTwoz** [Sayrix/ticket-bot#35]
Someone can help me with this error?

C:\Users\Joao\Documents\bot-faithmc\node_modules\discord.js\src\client\websocket\WebSocketManager.js:245
        throw new Error(WSCodes[error.code]);
              ^

Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\Joao\Documents\bot-faithmc\node_modules\discord.js\src\client\websocket\WebSocketManager.js:245:15)
    at async Client.login (C:\Users\Joao\Documents\bot-faithmc\node_modules\discord.js\src\client\Client.js:254:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}

**Comment by gybeny** [comment]
![image](https://user-images.githubusercontent.com/76707824/174123216-815bf6f9-23cc-4e6e-9b53-15dc595652e8.png)
![image](https://user-images.githubusercontent.com/76707824/174123135-219e643e-35cf-4752-aa36-96b33106f53e.png)
Enable this
