### ISSUE TITLE
error

### ISSUE THREAD

**Issue by roonieee** [Sayrix/ticket-bot#40]
i keep having this error while trying to open a ticket

C:\asd\ticket-bot-main\node_modules\discord.js\src\structures\PermissionOverwrites.js:184
    if (!userOrRole) throw new TypeError('INVALID_TYPE', 'parameter', 'User nor a Role');
                           ^

TypeError [INVALID_TYPE]: Supplied parameter is not a User nor a Role.
    at PermissionOverwrites.resolve (C:\asd\ticket-bot-main\node_modules\discord.js\src\structures\PermissionOverwrites.js:184:28)
    at C:\asd\ticket-bot-main\node_modules\discord.js\src\managers\GuildChannelManager.js:145:81
    at Array.map (<anonymous>)
    at GuildChannelManager.create (C:\asd\ticket-bot-main\node_modules\discord.js\src\managers\GuildChannelManager.js:145:51)
    at Object.execute (C:\asd\ticket-bot-main\events\interactionCreate.js:15:34)
    at Client.<anonymous> (C:\asd\ticket-bot-main\index.js:57:46)
    at Client.emit (node:events:549:35)
    at InteractionCreateAction.handle (C:\asd\ticket-bot-main\node_modules\discord.js\src\client\actions\InteractionCreate.js:83:12)
    at module.exports [as INTERACTION_CREATE] (C:\asd\ticket-bot-main\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\asd\ticket-bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:346:31) {
  [Symbol(code)]: 'INVALID_TYPE'
}

**Comment by DOSEV5** [comment]
I have the same issue. Developer said that I didn't configure it right. But I did.

**Comment by Migueldeeteenaa** [comment]
I have the same problem from time to time. Any solution?

**Comment by Migueldeeteenaa** [comment]
> I have the same issue. Developer said that I didn't configure it right. But I did.
