### ISSUE TITLE
Bot launch problem

### ISSUE THREAD

**Issue by AZDFR** [Sayrix/ticket-bot#44]
Hello, I can't launch the bot with both commands. Here is the error message

DiscordAPIError[20012]: You are not authorized to perform this action on this application
    at SequentialHandler.runRequest (/home/debian/botticket/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:198:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/debian/botticket/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:99:20) {
  rawError: {
    message: 'You are not authorized to perform this action on this application',
    code: 20012
  },
  code: 20012,
  status: 403,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/924674961958912010/commands'
}

**Comment by Migueldeeteenaa** [comment]
Good! You have to activate these three options within the Discord Developer. ( https://i.gyazo.com/41cf0d48ff612a0512634f8ea01310d1.png )

https://discord.com/developers/applications
