### ISSUE TITLE
Bot issue

### ISSUE THREAD

**Issue by Squidkiller01** [Sayrix/ticket-bot#45]
I tried to change the things such as token ID and such to match those of the bot I need this on, however the server keeps giving errors upon starting. Can you try to read these and see what the issue is?

Console log:

[WISP] Server marked as STARTING
[WISP] Checking size of server data directory...
[WISP] Disk Usage: 30M / 1028M
[WISP] Ensuring file permissions.
[WISP] Running server preflight.
[WISP] Starting server container.
:/home/container$ if [[ -d .git ]] && [[ 0 == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install --production; fi; /usr/local/bin/node /home/container/index.js
npm WARN ticket-bot@1.0.0 license should be a valid SPDX license expression

audited 78 packages in 0.454s
5 packages are looking for funding
run `npm fund` for details
found 1 moderate severity vulnerability
run `npm audit fix` to fix them, or `npm audit` for details
internal/modules/cjs/loader.js:818
throw err;
^
Error: Cannot find module 'node:events'
Require stack:
- /home/container/node_modules/discord.js/src/client/BaseClient.js
- /home/container/node_modules/discord.js/src/index.js
- /home/container/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/home/container/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/home/container/node_modules/discord.js/src/client/BaseClient.js',
'/home/container/node_modules/discord.js/src/index.js',
'/home/container/index.js'
]
}
[WISP] Server marked as OFF
[WISP] ---------- Detected server process in a crashed state! ----------
[WISP] Exit code: 1
[WISP] Out of Memory: false
[WISP] Error Response: 
[WISP] Server process detected as entering a crashed state; rebooting.

**Comment by AL280** [comment]
you didnt install all the modules required
