### ISSUE TITLE
Close Ticket don't work

### ISSUE THREAD

**Issue by alexistb2904** [Sayrix/ticket-bot#47]
Here my error

/app/node_modules/got/index.js:115
                                        err = new got.ParseError(e, statusCode, opts);
                                              ^
ErrorClass [ParseError]: Unexpected token '<' at 1:1 in https://hastebin.com/documents
<!DOCTYPE html>
^
    at /app/node_modules/got/index.js:115:12
    at BufferStream.<anonymous> (/app/node_modules/read-all-stream/index.js:64:3)
    at BufferStream.emit (node:events:525:35)
    at finishMaybe (/app/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/app/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at BufferStream.Writable.end (/app/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at IncomingMessage.onend (node:internal/streams/readable:693:10)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12) {
  host: 'hastebin.com',
  hostname: 'hastebin.com',
  method: 'POST',
  path: '/documents',
  statusCode: 503,
  statusMessage: 'Service Unavailable'

**Comment by JasonWu55** [comment]
Me too

**Comment by DonPedroTV** [comment]
change address to "http://donpedrotv.pl:8080/"
![image](https://user-images.githubusercontent.com/44004311/186133377-fe23cd8d-66e1-4359-8a9a-c5b70aebd772.png)
This is my server that I put up quickly
