### ISSUE TITLE
DiscordAPIError[10002]: Unknown Application

### ISSUE THREAD

**Issue by MrKossair** [Sayrix/ticket-bot#59]
Hey!

I got this error:
```
DiscordAPIError[10002]: Unknown Application
    at SequentialHandler.runRequest (C:\Users\membe\Desktop\BloomBot\ticket-bot-main\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js:198:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\membe\Desktop\BloomBot\ticket-bot-main\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js:99:20) {
  rawError: { message: 'Unknown Application', code: 10002 },
  code: 10002,
  status: 404,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/959566320310050896/commands'
}
```

when i use the "node deploy-commands.js"

can anybody help me?

**Comment by Sayrix** [comment]
Are you sure you set an correct client id?

**Comment by MrKossair** [comment]
yes because when is run node . the bot works fine but the commands are not

**Comment by Sayrix** [comment]
the clientId to set in the config is not the server id it's the id of the discord bot

**Comment by MrKossair** [comment]
the client id is the server id right?

**Comment by MrKossair** [comment]
oh

**Comment by MrKossair** [comment]
i see

**Comment by Sayrix** [comment]
re try with the id of the bot

**Comment by Sayrix** [comment]
![brave_nDR1xPMWmN](https://user-images.githubusercontent.com/43046854/194705914-f2ca82ab-d7de-4ec0-8b83-a1f75ef3fe63.png)

**Comment by MrKossair** [comment]
Ohh yeah i see now its working thanks

**Comment by Sayrix** [comment]
btw you can add a star to the repo
