### ISSUE TITLE
Ticket delete | hastebin

### ISSUE THREAD

**Issue by j0e1337** [Sayrix/ticket-bot#67]
There are still connect issues with hastebin => ticket delete stuff don't work => bot crash

**Comment by j0e1337** [comment]
`/home/bott/dsc/bot2/ticket-bot/node_modules/got/index.js:115
					err = new got.ParseError(e, statusCode, opts);
					      ^
ErrorClass [ParseError]: Unexpected token '<' at 1:1 in https://hastebin.com/documents
<!DOCTYPE html>
^
    at /home/bott/dsc/bot2/ticket-bot/node_modules/got/index.js:115:12
    at BufferStream.<anonymous> (/home/bott/dsc/bot2/ticket-bot/node_modules/read-all-stream/index.js:64:3)
    at BufferStream.emit (node:events:538:35)
    at finishMaybe (/home/bott/dsc/bot2/ticket-bot/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/home/bott/dsc/bot2/ticket-bot/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at BufferStream.Writable.end (/home/bott/dsc/bot2/ticket-bot/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at IncomingMessage.onend (node:internal/streams/readable:693:10)
    at Object.onceWrapper (node:events:645:28)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12) {
  host: 'hastebin.com',
  hostname: 'hastebin.com',
  method: 'POST',
  path: '/documents',
  statusCode: 503,
  statusMessage: 'Service Unavailable'
}
`

**Comment by j0e1337** [comment]
https://i.imgur.com/m1YVUM4.png

**Comment by Sayrix** [comment]
https://github.com/Sayrix/ticket-bot/discussions/55

**Comment by yurseli** [comment]
> me/bott/dsc/bot2/ticket-bot/node_modules/got/index.js:115

link dont work

**Comment by j0e1337** [comment]
> > me/bott/dsc/bot2/ticket-bot/node_modules/got/index.js:115
> 
> link dont work

https://imgur.com/m1YVUM4 should work

**Comment by Sayrix** [comment]
https://github.com/Sayrix/Ticket-Bot/discussions/69
