### ISSUE TITLE
DiscordAPIError[50035]: Invalid Form Body

### ISSUE THREAD

**Issue by tobiasReichel** [Sayrix/Ticket-Bot#82]
Fresh Copy of bot 

Configs Changed with my Client ID and Bot Token
everything else is untouched

```
(node:4161032) DeprecationWarning: The SelectMenuBuilder class is deprecated, use StringSelectMenuBuilder instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:4161032) DeprecationWarning: The SelectMenuOptionBuilder class is deprecated, use StringSelectMenuOptionBuilder instead.
(node:4161032) DeprecationWarning: BaseInteraction#isSelectMenu() is deprecated. Use BaseInteraction#isStringSelectMenu() instead.
DiscordAPIError[50035]: Invalid Form Body
parent_id[NUMBER_TYPE_COERCE]: Value "" is not snowflake.
    at SequentialHandler.runRequest (/root/git/Ticket-Bot/node_modules/@discordjs/rest/dist/index.js:667:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/root/git/Ticket-Bot/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/root/git/Ticket-Bot/node_modules/@discordjs/rest/dist/index.js:910:22)
    at async GuildChannelManager.create (/root/git/Ticket-Bot/node_modules/discord.js/src/managers/GuildChannelManager.js:169:18) {
  requestBody: {
    files: undefined,
    json: {
      name: 'Ticket-0',
      topic: undefined,
      type: undefined,
      nsfw: undefined,
      bitrate: undefined,
      user_limit: undefined,
      parent_id: '',
      position: undefined,
      permission_overwrites: [Array],
      rate_limit_per_user: undefined,
      rtc_region: undefined,
      video_quality_mode: undefined,
      available_tags: undefined,
      default_reaction_emoji: undefined,
      default_auto_archive_duration: undefined,
      default_sort_order: undefined
    }
  },
  rawError: {
    code: 50035,
    errors: { parent_id: [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/guilds/1040711282506076221/channels'
} Promise {
  <rejected> DiscordAPIError[50035]: Invalid Form Body
  parent_id[NUMBER_TYPE_COERCE]: Value "" is not snowflake.
      at SequentialHandler.runRequest (/root/git/Ticket-Bot/node_modules/@discordjs/rest/dist/index.js:667:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async SequentialHandler.queueRequest (/root/git/Ticket-Bot/node_modules/@discordjs/rest/dist/index.js:464:14)
      at async REST.request (/root/git/Ticket-Bot/node_modules/@discordjs/rest/dist/index.js:910:22)
      at async GuildChannelManager.create (/root/git/Ticket-Bot/node_modules/discord.js/src/managers/GuildChannelManager.js:169:18) {
    requestBody: { files: undefined, json: [Object] },
    rawError: { code: 50035, errors: [Object], message: 'Invalid Form Body' },
    code: 50035,
    status: 400,
    method: 'POST',
    url: 'https://discord.com/api/v10/guilds/1040711282506076221/channels'
  }
} undefined
```

**Comment by tobiasReichel** [comment]
Ignore that i was just a bit brain dead
